# SPDX-License-Identifier: MIT

name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 
jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Install dependencies & setup project
      run: |
        poetry install --sync --no-interaction
 
    - name: Run the tests
      run: poetry run pytest .